
volumes:
  postgres:
    external: true
  pgadmin:
    external: true
  node_modules:

services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    env_file:
      - docker.env
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - api
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    restart: unless-stopped
    image: dpage/pgadmin4
    ports:
      - 8080:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    env_file:
      - docker.env
    networks:
      - api
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - api
networks:
  api:
    driver: bridge

