
volumes:
  postgres:
    external: true
  pgadmin:
    external: true
  node_modules:

services:
  # api:
  #   build:
  #     context: ./
  #     target: dev
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   volumes:
  #     - .:/api
  #     - node_modules:/api/node_modules
  #   command: npm run start:dev
  #   ports:
  #     - 3001:3001
  #   env_file:
  #     - .env.development
  #   networks:
  #     - elriolibros
  #   depends_on:
  #     - postgres
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    env_file:
      - docker.env
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - elriolibros
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    restart: always
    image: dpage/pgadmin4
    ports:
      - 8080:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    env_file:
      - docker.env
    networks:
      - elriolibros
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always
    networks:
      - elriolibros
networks:
  elriolibros:
    driver: bridge

